# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - run: npm test

  performance:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        measure: ['measure-cli-build.js','measure-dev-server.js']
        moduleMultiplier: ['1','10']
        node-version: [14.x]
        transpiler: ['typescript', 'babel']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - working-directory: ./performance
      run: npm i
    - name: Measure ${{ matrix.measure }} with ${{ matrix.transpiler }} x ${{ matrix.moduleMultiplier }} on Node.js ${{ matrix.node-version }}
      working-directory: ./performance
      run: node ${{ matrix.measure }}
      env:
        transpiler: ${{ matrix.transpiler }}
        moduleMultiplier: ${{ matrix.moduleMultiplier }}
